version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5435:5432"
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local
